build:
  version: 1.0
spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: 1234
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

eureka:
  instance:
    hostname: localhost

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  shutdown:
    enabled: true
  info:
   env:
    enabled: true
    
endpoints:
 shutdown:
  enabled: true
  
info:
  app:
     name: customer-service
     description: This is customer service

   
