spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: 1234
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      highlight_sql: true

eureka:
  instance:
    hostname: localhost

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:8761/eureka/
