build:
  version: "1.0 - order-service"
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        
management:
  endpoints:
    web:
      exposure:
        enabled: true
  info:
    env:
      enabled: true
  endpoint:  
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info: 
  app:
    name: order-service
    description: This is order service
    

eureka:
  instance:
    hostname: localhost

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:8761/eureka/
