spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

eureka:
  instance:
    hostname: localhost

  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:8761/eureka/
